# Generated by Django 2.2 on 2020-02-17 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0001_initial'),
        ('cash', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=256, null=True)),
                ('status', models.CharField(blank=True, choices=[('007', 'Completed'), ('600', 'Returned'), ('000', 'Voided')], default='007', max_length=32)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('system', models.CharField(blank=True, default='Physical Cash', max_length=256)),
                ('currency', models.CharField(blank=True, default='', max_length=64)),
                ('supplier_name', models.CharField(blank=True, default='', max_length=256)),
                ('cash', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cash.Cash')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.Supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=256, null=True)),
                ('status', models.CharField(blank=True, choices=[('007', 'Completed'), ('600', 'Returned'), ('000', 'Voided')], default='007', max_length=32)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('system', models.CharField(blank=True, default='Physical Cash', max_length=256)),
                ('currency', models.CharField(blank=True, default='', max_length=64)),
                ('customer_name', models.CharField(blank=True, default='', max_length=256)),
                ('cash', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cash.Cash')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesReturnReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=256, null=True)),
                ('status', models.CharField(blank=True, choices=[('007', 'Completed'), ('600', 'Returned'), ('000', 'Voided')], default='007', max_length=32)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('system', models.CharField(blank=True, default='Physical Cash', max_length=256)),
                ('currency', models.CharField(blank=True, default='', max_length=64)),
                ('customer_name', models.CharField(blank=True, default='', max_length=256)),
                ('cash', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cash.Cash')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('salesreceipt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='receipt.SalesReceipt')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=256, null=True)),
                ('status', models.CharField(blank=True, choices=[('007', 'Completed'), ('600', 'Returned'), ('000', 'Voided')], default='007', max_length=32)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('system', models.CharField(blank=True, default='Physical Cash', max_length=256)),
                ('currency', models.CharField(blank=True, default='', max_length=64)),
                ('supplier_name', models.CharField(blank=True, default='', max_length=256)),
                ('cash', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cash.Cash')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('purchasesreceipt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='receipt.PurchaseReceipt')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.Supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
