# Generated by Django 2.2 on 2020-02-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasereceipt',
            name='status',
            field=models.CharField(blank=True, choices=[('007', 'Completed'), ('600', 'Returned'), ('000', 'Voided')], default='Completed', max_length=32),
        ),
        migrations.AlterField(
            model_name='purchasereturnreceipt',
            name='status',
            field=models.CharField(blank=True, choices=[('007', 'Completed'), ('600', 'Returned'), ('000', 'Voided')], default='Completed', max_length=32),
        ),
        migrations.AlterField(
            model_name='salesreceipt',
            name='status',
            field=models.CharField(blank=True, choices=[('007', 'Completed'), ('600', 'Returned'), ('000', 'Voided')], default='Completed', max_length=32),
        ),
        migrations.AlterField(
            model_name='salesreturnreceipt',
            name='status',
            field=models.CharField(blank=True, choices=[('007', 'Completed'), ('600', 'Returned'), ('000', 'Voided')], default='Completed', max_length=32),
        ),
    ]
