# Generated by Django 2.2 on 2020-02-18 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='ghpgps',
            new_name='pgps',
        ),
    ]
