# Generated by Django 2.2 on 2020-02-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='status',
            field=models.CharField(blank=True, choices=[('007', 'Paid'), ('419', 'Unpaid'), ('600', 'Returned'), ('202', 'Overdue'), ('212', 'Partly Paid'), ('000', 'Voided')], default='Unpaid', max_length=32),
        ),
        migrations.AlterField(
            model_name='purchasereturninvoice',
            name='status',
            field=models.CharField(blank=True, choices=[('007', 'Paid'), ('419', 'Unpaid'), ('600', 'Returned'), ('202', 'Overdue'), ('212', 'Partly Paid'), ('000', 'Voided')], default='Unpaid', max_length=32),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='status',
            field=models.CharField(blank=True, choices=[('007', 'Paid'), ('419', 'Unpaid'), ('600', 'Returned'), ('202', 'Overdue'), ('212', 'Partly Paid'), ('000', 'Voided')], default='Unpaid', max_length=32),
        ),
        migrations.AlterField(
            model_name='salesreturninvoice',
            name='status',
            field=models.CharField(blank=True, choices=[('007', 'Paid'), ('419', 'Unpaid'), ('600', 'Returned'), ('202', 'Overdue'), ('212', 'Partly Paid'), ('000', 'Voided')], default='Unpaid', max_length=32),
        ),
    ]
